In [23]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Add

In [24]:
initializer = tf.random_normal_initializer()

tensor = initializer(shape=(5,))  # Tensor dengan 5 elemen
print(tensor.numpy())  # Melihat nilai yang dihasilkan

[-0.02494303 -0.02391509 -0.07254764  0.0265321  -0.02940079]


In [25]:
tensor_np = np.array([[1, 2, 3], [4, 5, 6]])

# Menampilkan array
print(tensor_np[-1])

[4 5 6]


In [26]:
input_shape = (5,3)  # dimensi terakhir = 5
units = 16 

print(input_shape[-1])

3


In [27]:
x = 0
for i in range(5):
    x = i

print(x)

4


In [28]:
input_shape = (2, 3, 4)
x1 = np.random.rand(*input_shape)
x2 = np.random.rand(*input_shape)
y = Add()([x1, x2])

In [29]:
vars(initializer)

{'mean': 0.0,
 'stddev': 0.05,
 'seed': None,
 '_random_generator': <tensorflow.python.ops.init_ops_v2._RandomGenerator at 0x1e43f2fad40>}

In [30]:
a = tf.constant( [[5,7],[2,1]])
b = tf.add(a,2)
c = b**2
d =tf. reduce_sum(c)
print(d)
print(c)

tf.Tensor(155, shape=(), dtype=int32)
tf.Tensor(
[[49 81]
 [16  9]], shape=(2, 2), dtype=int32)


In [31]:
def base_model():
  inputs = tf.keras.Input(shape=(784,), name='digits')
  x = tf.keras.layers.Dense(64, activation='relu', name='dense_1')(inputs)
  x = tf.keras.layers.Dense(64, activation='relu', name='dense_2')(x)
  outputs = tf.keras.layers.Dense(10, activation='softmax', name='predictions')(x)
  model = tf.keras.Model(inputs=inputs, outputs=outputs)
  return model

In [32]:
model = base_model()

In [33]:
model.trainable_weights

[<KerasVariable shape=(784, 64), dtype=float32, path=dense_1/kernel>,
 <KerasVariable shape=(64,), dtype=float32, path=dense_1/bias>,
 <KerasVariable shape=(64, 64), dtype=float32, path=dense_2/kernel>,
 <KerasVariable shape=(64,), dtype=float32, path=dense_2/bias>,
 <KerasVariable shape=(64, 10), dtype=float32, path=predictions/kernel>,
 <KerasVariable shape=(10,), dtype=float32, path=predictions/bias>]

In [34]:
@tf.function
def f(x):
  if x < 0:
    x = -x
  return x
print(tf.autograph.to_code(f.python_function))

def tf__f(x):
    with ag__.FunctionScope('f', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()

        def get_state():
            return (x,)

        def set_state(vars_):
            nonlocal x
            (x,) = vars_

        def if_body():
            nonlocal x
            x = -ag__.ld(x)

        def else_body():
            nonlocal x
            pass
        ag__.if_stmt(ag__.ld(x) < 0, if_body, else_body, get_state, set_state, ('x',), 1)
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [36]:
a = tf.Variable(1.0)
a.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [37]:
strategy = tf.distribute.MirroredStrategy()

print('NUmber of device : {}'.format(strategy.num_replicas_in_sync))

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)
NUmber of device : 1


In [47]:
def test(x):
    return x**2

list(map(test,[32434,23324324,324324,243]))


[1051964356, 544024090056976, 105186056976, 59049]